const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const BACKEND=window.TEMU_BACKEND||'https://yidong.dianleida.net:21998';
const state={tab:'url',files:[],urls:[],batch:null,selectedId:null,page:1,pageSize:20,timer:null};
const el={tabs:$$('.tab'),panes:$$('.tab-pane'),status:$('#service-status'),urls:$('#url-textarea'),import:$('#import-text'),clearUrl:$('#clear-url'),startUrl:$('#start-url'),fileInput:$('#file-input'),drop:$('#dropzone'),clearFiles:$('#clear-files'),startFiles:$('#start-files'),preview:$('#preview'),previewCount:$('#preview-count'),previewEta:$('#preview-eta'),previewGrid:$('#preview-grid'),previewClear:$('#preview-clear'),results:$('#results'),queue:$('#source-queue'),grid:$('#results-grid'),empty:$('#result-empty'),count:$('#results-count'),progressText:$('#batch-progress-text'),current:$('#batch-current'),progressBar:$('#batch-progress-bar'),pageCurrent:$('#page-current'),pageTotal:$('#page-total'),pageSize:$('#page-size'),exportJson:$('#export-json'),exportCsv:$('#export-csv')};
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escapeAttr(v){return escapeHtml(v)}
async function api(path,options){const response=await fetch(BACKEND+path,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||`请求失败 ${response.status}`);return data}
async function health(){try{const data=await api('/api/health');el.status.classList.add('online');$('span:last-child',el.status).textContent=`服务在线 · ${data.mode==='mock'?'演示模式':'真实设备'}`}catch{$('span:last-child',el.status).textContent='服务未连接'}}health();
el.tabs.forEach(t=>t.onclick=()=>{state.tab=t.dataset.tab;el.tabs.forEach(x=>x.classList.toggle('active',x===t));el.panes.forEach(x=>x.classList.toggle('active',x.dataset.pane===state.tab));renderPreview()});
el.urls.oninput=()=>renderPreview();el.clearUrl.onclick=()=>{el.urls.value='';renderPreview()};el.import.onclick=()=>{const input=document.createElement('input');input.type='file';input.accept='.txt,.csv';input.onchange=()=>{const file=input.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{el.urls.value=String(reader.result||'');renderPreview()};reader.readAsText(file)};input.click()};
el.drop.ondragover=e=>{e.preventDefault();el.drop.classList.add('drag')};el.drop.ondragleave=()=>el.drop.classList.remove('drag');el.drop.ondrop=e=>{e.preventDefault();el.drop.classList.remove('drag');addFiles(e.dataTransfer.files)};el.fileInput.onchange=e=>addFiles(e.target.files);
function addFiles(list){for(const file of list){if(!file.type.startsWith('image/')||file.size>4*1024*1024)continue;state.files.push({file,id:crypto.randomUUID(),name:file.name,previewUrl:URL.createObjectURL(file),status:'queued'})}renderPreview()}
el.clearFiles.onclick=()=>{state.files=[];el.fileInput.value='';renderPreview()};el.previewClear.onclick=()=>{state.files=[];el.urls.value='';renderPreview()};
function pending(){if(state.tab==='url')return el.urls.value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map((url,index)=>({id:`url-${index}`,name:url,previewUrl:url,status:'queued'}));return state.files}
function label(status){return({queued:'等待',running:'搜索中',succeeded:'完成',failed:'失败'})[status]||status}
function renderPreview(){const items=pending();el.preview.hidden=!items.length;el.previewCount.textContent=items.length;el.previewEta.textContent=items.length?`约 ${items.length} 分钟`:'--';el.previewGrid.innerHTML=items.map(item=>`<div class="preview-item"><img src="${escapeAttr(item.previewUrl)}" alt=""><span class="status ${item.status}">${label(item.status)}</span></div>`).join('');el.startUrl.disabled=!items.length;el.startFiles.disabled=!state.files.length}
el.startFiles.onclick=async()=>{const fd=new FormData();state.files.forEach(item=>fd.append('images',item.file));await submit('/api/batches/files',{method:'POST',body:fd})};el.startUrl.onclick=async()=>{const urls=pending().map(x=>x.name);await submit('/api/batches/urls',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({urls})})};
async function submit(path,options){try{el.results.hidden=false;const data=await api(path,options);state.batch=data.batch;state.selectedId=data.batch.items[0]?.id;localStorage.setItem('temuBatchId',data.batch.id);renderBatch();startPolling()}catch(error){alert(`提交失败：${error.message}`)}}
function startPolling(){clearInterval(state.timer);state.timer=setInterval(loadBatch,1500);loadBatch()}
async function loadBatch(){if(!state.batch)return;try{const data=await api(`/api/batches/${state.batch.id}`);state.batch=data.batch;if(!state.selectedId)state.selectedId=data.batch.items.find(x=>x.status==='succeeded')?.id||data.batch.items[0]?.id;renderBatch();if(['completed','failed'].includes(state.batch.status)){clearInterval(state.timer);state.timer=null}}catch(error){console.error(error)}}
function renderBatch(){const batch=state.batch;if(!batch)return;const s=batch.summary;const done=s.succeeded+s.failed;el.progressText.textContent=`整体进度 ${done} / ${s.total}`;el.progressBar.style.width=`${s.total?done/s.total*100:0}%`;const running=batch.items.find(x=>x.status==='running');el.current.textContent=running?`正在处理：${running.name}`:batch.status==='completed'?'批次已完成':'';el.queue.innerHTML=batch.items.map(item=>`<button class="source-item ${item.id===state.selectedId?'active':''}" data-id="${item.id}"><img src="${escapeAttr(imageSrc(item.previewUrl||item.source))}" alt=""><span><strong>${escapeHtml(item.name)}</strong><small>${label(item.status)} · ${item.productCount||0} 个商品${item.durationMs?` · ${Math.round(item.durationMs/1000)} 秒`:''}</small>${item.status==='failed'?`<small class="retry" data-retry="${item.id}">${escapeHtml(item.error?.message||'点击重试')}</small>`:''}</span></button>`).join('');$$('.source-item',el.queue).forEach(button=>button.onclick=e=>{const retry=e.target.dataset.retry;if(retry){retryItem(retry);return}state.selectedId=button.dataset.id;state.page=1;renderBatch()});renderProducts()}
async function retryItem(itemId){try{await api(`/api/batches/${state.batch.id}/items/${itemId}/retry`,{method:'POST'});startPolling()}catch(error){alert(`重试失败：${error.message}`)}}
function selectedItem(){return state.batch?.items.find(x=>x.id===state.selectedId)}
function renderProducts(){const item=selectedItem();const products=item?.products||[];el.count.textContent=item?`${escapeHtml(item.name)} · ${products.length} 条`:'';el.empty.hidden=products.length>0;el.grid.hidden=!products.length;if(!products.length){el.empty.textContent=item?.status==='failed'?`搜索失败：${item.error?.message||'未知错误'}`:item?.status==='running'?'正在图搜并读取商品模型…':'等待该图片开始处理';el.grid.innerHTML='';return}const pages=Math.max(1,Math.ceil(products.length/state.pageSize));state.page=Math.min(state.page,pages);el.pageCurrent.textContent=state.page;el.pageTotal.textContent=pages;const slice=products.slice((state.page-1)*state.pageSize,state.page*state.pageSize);el.grid.innerHTML=slice.map(p=>`<article class="result-card"><div class="result-thumb" style="background-image:url('${escapeAttr(p.imageUrl)}')"><span class="source-tag">源图 → 同款</span></div><div class="result-body"><h4 class="result-title">${escapeHtml(p.title||'Temu 商品')}</h4><div class="result-price"><span class="price-main">${escapeHtml(p.priceText||'')}</span>${p.marketPriceText?`<span class="price-old">${escapeHtml(p.marketPriceText)}</span>`:''}</div><div class="result-meta">${p.salesText?`<span>${escapeHtml(p.salesText)}</span>`:''}${p.discountText?`<span>${escapeHtml(p.discountText)}</span>`:''}${p.isAd?'<span>AD</span>':''}</div><div class="result-actions"><a href="${escapeAttr(p.productUrl||'#')}" target="_blank" rel="noopener">打开商品</a><a class="alt copy-id" data-id="${escapeAttr(p.goodsId)}">复制 ID</a></div></div></article>`).join('');$$('.copy-id',el.grid).forEach(a=>a.onclick=()=>navigator.clipboard.writeText(a.dataset.id))}
$$('.page-btn').forEach(button=>button.onclick=()=>{const products=selectedItem()?.products||[];const pages=Math.max(1,Math.ceil(products.length/state.pageSize));if(button.dataset.page==='first')state.page=1;if(button.dataset.page==='prev')state.page=Math.max(1,state.page-1);if(button.dataset.page==='next')state.page=Math.min(pages,state.page+1);if(button.dataset.page==='last')state.page=pages;renderProducts()});el.pageSize.onchange=e=>{state.pageSize=parseInt(e.target.value)||20;state.page=1;renderProducts()};
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove()}el.exportJson.onclick=()=>state.batch&&download(`${BACKEND}/api/batches/${state.batch.id}/export?format=json`,'temu-results.json');el.exportCsv.onclick=()=>state.batch&&download(`${BACKEND}/api/batches/${state.batch.id}/export?format=csv`,'temu-results.csv');
const saved=localStorage.getItem('temuBatchId');if(saved){state.batch={id:saved};el.results.hidden=false;startPolling()}renderPreview();
