(function(){
'use strict';
const DEFAULT_API_BASE=window.TEMU_BACKEND||'https://yidong.dianleida.net:21998';
const FILE_RENDER_BATCH=30;
const POLL_INTERVAL=1500;
const CLEANUP_STORAGE_KEY='temuPendingCleanupBatchIds';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const on=(el,ev,fn)=>el&&el.addEventListener(ev,fn);
const h=(tag,attrs={},...children)=>{const el=document.createElement(tag);for(const k in attrs){if(k==='class')el.className=attrs[k];else if(k==='html')el.innerHTML=attrs[k];else if(k.startsWith('on'))el.addEventListener(k.slice(2).toLowerCase(),attrs[k]);else el.setAttribute(k,attrs[k]);}children.flat().forEach(c=>{if(c==null)return;el.appendChild(typeof c==='string'?document.createTextNode(c):c)});return el};
const state={apiBase:getApiBase(),activeTab:'link',files:[],urls:[],tableUrls:[],fileRenderCount:0,batch:null,pollTimer:null,pollStartedAt:0,elapsedTimer:null,isSearching:false,cancelRequested:false,resultRows:[],pagination:{currentPage:1,pageSize:20,totalItems:0},ownedBatchIds:readCleanupIds(),cleanupSent:new Set()};
const emptySvg='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"%3E%3Crect width="100" height="100" fill="%23f5f7fb"/%3E%3Ctext x="50" y="55" text-anchor="middle" font-size="12" fill="%238b94b0"%3E无图%3C/text%3E%3C/svg%3E';
function readCleanupIds(){try{return new Set(JSON.parse(localStorage.getItem(CLEANUP_STORAGE_KEY)||'[]'))}catch{return new Set()}}
function saveCleanupIds(){localStorage.setItem(CLEANUP_STORAGE_KEY,JSON.stringify([...state.ownedBatchIds]))}
function registerOwnedBatch(id){if(!id)return;state.ownedBatchIds.add(id);saveCleanupIds()}
function unregisterOwnedBatch(id){state.ownedBatchIds.delete(id);state.cleanupSent.delete(id);saveCleanupIds()}
function getApiBase(){return(localStorage.getItem('temuApiBase')||DEFAULT_API_BASE).replace(/\/+$/,'')}
function setApiBase(v){state.apiBase=String(v||DEFAULT_API_BASE).replace(/\/+$/,'');localStorage.setItem('temuApiBase',state.apiBase)}
async function fetchJson(path,options={}){const res=await fetch(state.apiBase+path,options);const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||`请求失败 ${res.status}`);return data}
function fmtTime(sec){if(!isFinite(sec)||sec<0)return'-';sec=Math.round(sec);if(sec<60)return`${sec}秒`;const m=Math.floor(sec/60),s=sec%60;if(m<60)return`${m}分${s}秒`;return`${Math.floor(m/60)}时${m%60}分`}
function fmtClock(sec){sec=Math.max(0,Math.round(sec));return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function label(status){return({queued:'等待中',running:'搜索中',succeeded:'已完成',failed:'失败',completed:'已完成',stopped:'已停止',interrupted:'已中断'})[status]||status||'-'}
function sourceImage(item){if(!item)return emptySvg;if(item.previewUrl)return item.previewUrl;if(item.source&&/^https?:\/\//i.test(item.source))return item.source;if(item.localUrl)return item.localUrl;return emptySvg}
function normalizeProduct(p,rank){return{rank:rank||p.rank||1,title:p.title||p.productTitle||'Temu 商品',image:p.imageUrl||p.image||p.thumbUrl||emptySvg,url:p.productUrl||p.url||'#',price:p.priceText||p.price||'',sales:p.salesText||p.sales||'',discount:p.discountText||'',goodsId:p.goodsId||p.goods_id||'',is_ad:p.isAd||p.is_ad||false,similarity:p.similarity}}
function setupTabs(){on($('#uploadTabs'),'click',e=>{const btn=e.target.closest('.upload-tab');if(!btn)return;switchTab(btn.dataset.tab)});}
function switchTab(name){state.activeTab=name;$$('.upload-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.upload-panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${name}`));updateSearchBtn()}
function setupBatchUpload(){const drop=$('#dropZone'),input=$('#fileInput');on(drop,'click',()=>input.click());on(input,'change',e=>handleFiles(e.target.files));['dragover','dragenter'].forEach(ev=>on(drop,ev,e=>{e.preventDefault();drop.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>on(drop,ev,e=>{e.preventDefault();drop.classList.remove('dragover')}));on(drop,'drop',e=>handleFiles(Array.from(e.dataTransfer.files).filter(f=>f.type.startsWith('image/'))));on($('#loadMoreFilesBtn'),'click',()=>{state.fileRenderCount=Math.min(state.fileRenderCount+FILE_RENDER_BATCH,state.files.length);renderFileList()})}
function handleFiles(fileList){const seen=new Set(state.files.map(f=>`${f.name}:${f.size}`));Array.from(fileList).forEach(file=>{if(!file.type.startsWith('image/')||file.size>4*1024*1024||seen.has(`${file.name}:${file.size}`))return;seen.add(`${file.name}:${file.size}`);const item={id:crypto.randomUUID(),name:file.name,size:file.size,file,dataUrl:null};state.files.push(item);const reader=new FileReader();reader.onload=()=>{item.dataUrl=reader.result;state.fileRenderCount=state.files.length;renderFileList();updateSearchBtn()};reader.readAsDataURL(file)});updateSearchBtn()}
function buildFileItem(item,idx,onRemove){const el=h('div',{class:'file-item'});el.appendChild(h('img',{src:item.dataUrl||item.url,alt:item.name||item.url,loading:'lazy'}));el.appendChild(h('div',{class:'file-item-name',title:item.name||item.url},item.name||shortUrl(item.url)));const rm=h('button',{class:'file-item-remove','aria-label':'移除'},'×');on(rm,'click',e=>{e.stopPropagation();onRemove()});el.appendChild(rm);return el}
function renderFileList(){const grid=$('#fileGrid');grid.innerHTML='';const total=state.files.length,shown=Math.min(state.fileRenderCount,total);$('#fileCount').textContent=`${total} 张`;$('#fileList').hidden=total===0;state.files.slice(0,shown).forEach((f,idx)=>grid.appendChild(buildFileItem(f,idx,()=>{URL.revokeObjectURL(f.previewUrl||'');state.files.splice(idx,1);state.fileRenderCount=Math.min(state.fileRenderCount,state.files.length);renderFileList();updateSearchBtn()})));$('#fileListMore').hidden=total<=shown;$('#fileShown').textContent=shown;$('#fileTotal').textContent=total}
function setupUrlPanel(){const ta=$('#urlTextarea'),file=$('#urlFileInput');on(ta,'input',()=>{clearTimeout(state._urlTimer);state._urlTimer=setTimeout(parseUrls,250)});on(ta,'paste',()=>{clearTimeout(state._urlTimer);state._urlTimer=setTimeout(parseUrls,100)});on(file,'change',async e=>{const f=e.target.files[0];if(!f)return;ta.value=await f.text();parseUrls()});on($('#clearUrlBtn'),'click',()=>{ta.value='';state.urls=[];$('#urlPreview').hidden=true;renderUrlGrid();updateSearchBtn()});on($('#previewUrlBtn'),'click',()=>{parseUrls();renderUrlGrid();$('#urlPreview').hidden=state.urls.length===0})}
function parseUrls(){const valid=$('#urlTextarea').value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).filter(u=>/^https?:\/\//i.test(u));state.urls=[...new Set(valid)].slice(0,100).map(url=>({url,name:url,status:'queued'}));$('#urlCount').textContent=`${state.urls.length} 条`;updateSearchBtn()}
function renderUrlGrid(){const grid=$('#urlGrid');grid.innerHTML='';state.urls.forEach((u,idx)=>grid.appendChild(buildFileItem({url:u.url,name:shortUrl(u.url)},idx,()=>{state.urls.splice(idx,1);$('#urlTextarea').value=state.urls.map(x=>x.url).join('\n');renderUrlGrid();parseUrls();$('#urlPreview').hidden=state.urls.length===0})))}
function shortUrl(url){return url.length>42?url.slice(0,42)+'...':url}
function setupTablePanel(){const drop=$('#tableDropZone'),input=$('#tableFileInput');on(drop,'click',()=>input.click());on(input,'change',e=>{const f=e.target.files[0];if(f)handleTableFile(f)});['dragover','dragenter'].forEach(ev=>on(drop,ev,e=>{e.preventDefault();drop.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>on(drop,ev,e=>{e.preventDefault();drop.classList.remove('dragover')}));on(drop,'drop',e=>{const f=Array.from(e.dataTransfer.files).find(x=>/\.(xlsx|xls|csv)$/i.test(x.name));if(f)handleTableFile(f)});on($('#clearTableBtn'),'click',()=>{state.tableUrls=[];$('#tableFileInfo').hidden=true;$('#tablePreview').hidden=true;input.value='';updateSearchBtn()});on($('#refreshTableUrlsBtn'),'click',refreshTableUrls);on($('#previewTableBtn'),'click',()=>{refreshTableUrls();renderTableGrid();$('#tablePreview').hidden=state.tableUrls.length===0})}
async function handleTableFile(file){try{const buf=await file.arrayBuffer();let text='';if(typeof XLSX!=='undefined'){const wb=XLSX.read(buf,{type:'array'});for(const name of wb.SheetNames)text+=XLSX.utils.sheet_to_csv(wb.Sheets[name])+'\n'}else{text=new TextDecoder().decode(buf)}const urls=[...new Set((text.match(/https?:\/\/[^\s"',;|}\]]+\.(?:jpg|jpeg|png|webp|gif|bmp|tiff?)(?:\?[^\s"',;|}\]]*)?/gi)||[]).map(u=>u.trim()))].slice(0,100);state.tableUrls=urls.map(url=>({url,name:url,status:'queued'}));$('#tableFileInfo').hidden=false;$('#tableFileName').textContent='📄 '+file.name;$('#tableUrlCount').textContent=`${urls.length} 条链接`;$('#tableUrlTextarea').value=urls.join('\n');$('#tableUrlTextarea').readOnly=false;$('#tablePreview').hidden=true;updateSearchBtn()}catch(e){alert('解析表格失败：'+e.message)}}
function refreshTableUrls(){const urls=[...new Set($('#tableUrlTextarea').value.split(/\r?\n/).map(s=>s.trim()).filter(u=>/^https?:\/\//i.test(u)))].slice(0,100);state.tableUrls=urls.map(url=>({url,name:url,status:'queued'}));$('#tableUrlCount').textContent=`${urls.length} 条链接`;updateSearchBtn()}
function renderTableGrid(){const grid=$('#tableGrid');grid.innerHTML='';state.tableUrls.forEach((u,idx)=>grid.appendChild(buildFileItem({url:u.url,name:shortUrl(u.url)},idx,()=>{state.tableUrls.splice(idx,1);$('#tableUrlTextarea').value=state.tableUrls.map(x=>x.url).join('\n');$('#tableUrlCount').textContent=`${state.tableUrls.length} 条链接`;renderTableGrid();updateSearchBtn()})))}
function getCurrentCount(){if(state.activeTab==='batch')return state.files.length;if(state.activeTab==='link')return state.urls.length;return state.tableUrls.length}
function clearCurrent(){if(state.activeTab==='batch'){state.files=[];$('#fileInput').value='';renderFileList()}else if(state.activeTab==='link'){$('#urlTextarea').value='';state.urls=[];$('#urlPreview').hidden=true;renderUrlGrid()}else{state.tableUrls=[];$('#tableFileInfo').hidden=true;$('#tablePreview').hidden=true;$('#tableFileInput').value=''}updateSearchBtn()}
function updateSearchBtn(){$('#searchBtn').disabled=getCurrentCount()===0||state.isSearching;$('#clearBtn').hidden=state.isSearching||getCurrentCount()===0}
async function startSearch(){if(state.isSearching)return;state.isSearching=true;state.cancelRequested=false;state.batch=null;state.resultRows=[];state.pagination.currentPage=1;resetProgress();updateSearchBtn();const t0=Date.now();try{let data;if(state.activeTab==='batch'){const fd=new FormData();state.files.forEach(f=>fd.append('images',f.file));data=await fetchJson('/api/temu/tasks/from-files',{method:'POST',body:fd})}else{const urls=(state.activeTab==='link'?state.urls:state.tableUrls).map(x=>x.url);data=await fetchJson('/api/temu/tasks/from-urls',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({urls})})}state.batch=data.task;registerOwnedBatch(state.batch.id);await fetchJson(`/api/temu/tasks/${state.batch.id}/search`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'}).catch(()=>null);$('#uploadTiming').hidden=false;$('#timingVal').textContent=((Date.now()-t0)/1000).toFixed(1);renderHistory();startPolling()}catch(e){alert('提交失败：'+e.message);state.isSearching=false;updateSearchBtn()}}
function resetProgress(){$('#progress-section').hidden=false;$('#progress-section').scrollIntoView({behavior:'smooth',block:'start'});$('#result-section').hidden=true;$('#progressStatus').textContent='准备中...';$('#progressFill').style.width='0%';$('#progressCurrent').textContent='0';$('#progressTotal').textContent='0';$('#progressPercent').textContent='0%';$('#downloadProgressText').textContent='0 / 0 · 0%';$('#downloadProgressFill').style.width='0%';$('#searchProgressText').textContent='0 / 0 · 0%';$('#searchProgressFill').style.width='0%';$('#foundProducts').textContent='0';$('#elapsedTime').textContent='00:00';$('#estimatedTime').textContent='-';$('#currentImage').textContent='-';$('#imageStatusList').innerHTML='';$('#imageStatusSection').hidden=false;$('#imageStatusSummary').textContent='0/0 已完成';$('#cancelBtn').hidden=false;$('#cancelBtn').disabled=false;$('#cancelBtn').textContent='⏹ 停止任务';state.pollStartedAt=Date.now()}
function startPolling(){stopPolling();poll();state.pollTimer=setInterval(poll,POLL_INTERVAL);state.elapsedTimer=setInterval(()=>{$('#elapsedTime').textContent=fmtClock((Date.now()-state.pollStartedAt)/1000)},1000)}
function stopPolling(){if(state.pollTimer)clearInterval(state.pollTimer);if(state.elapsedTimer)clearInterval(state.elapsedTimer);state.pollTimer=null;state.elapsedTimer=null}
async function poll(){if(!state.batch?.id)return;try{const data=await fetchJson(`/api/temu/tasks/${state.batch.id}`);state.batch=data.task;applyProgress();renderHistory();if(['completed','failed','stopped','interrupted'].includes(state.batch.status)){stopPolling();state.isSearching=false;$('#cancelBtn').hidden=true;await showResults();updateSearchBtn()}}catch(e){console.warn(e)}}
function applyProgress(){const b=state.batch,s=b.summary||{total:0,succeeded:0,failed:0,queued:0,running:0};const done=s.succeeded+s.failed,total=s.total||0,pct=total?Math.round(done/total*100):0;$('#progressCurrent').textContent=done;$('#progressTotal').textContent=total;$('#progressPercent').textContent=pct+'%';$('#progressFill').style.width=pct+'%';$('#downloadProgressText').textContent=`${total} / ${total} · ${total?100:0}%`;$('#downloadProgressFill').style.width=total?'100%':'0%';$('#searchProgressText').textContent=`${done} / ${total} · ${pct}%`;$('#searchProgressFill').style.width=pct+'%';const running=b.items.find(x=>x.status==='running');// 显示并发 worker 进度
const concurrency=b.concurrency||1;const active=b.activeWorkers||0;let statusText=running?`搜索中 ${done}/${total}`:label(b.status);if(concurrency>1&&active>0){statusText=`并发 ${active}/${concurrency} · ${done}/${total}`}$('#progressStatus').textContent=statusText;$('#currentImage').textContent=running?running.name:`${label(b.status)}：${done}/${total} 张`;const products=b.items.reduce((sum,item)=>sum+(item.productCount||item.products?.length||0),0);$('#foundProducts').textContent=products;if(done>0&&done<total){const elapsed=Math.max(1,(Date.now()-state.pollStartedAt)/1000);$('#estimatedTime').textContent=fmtTime(elapsed/done*(total-done))}else{$('#estimatedTime').textContent='-'}const list=$('#imageStatusList');list.innerHTML='';b.items.forEach(item=>list.appendChild(h('div',{class:'image-status-row'},h('span',{class:'name',title:item.name},item.name),h('span',{class:`status-badge ${item.status}`},label(item.status)),h('span',{class:'meta-item'},`${item.productCount||item.products?.length||0} 个结果`))));$('#imageStatusSummary').textContent=`${done}/${total} 已完成`}
async function showResults(){flattenResults();renderResults()}
function flattenResults(){const rows=[];(state.batch?.items||[]).forEach(item=>{rows.push({item,products:(item.products||[]).map((p,i)=>normalizeProduct(p,i+1))})});state.resultRows=rows;state.pagination.totalItems=rows.length}
function renderResults(){$('#result-section').hidden=false;const totalProducts=state.resultRows.reduce((s,r)=>s+r.products.length,0);$('#resultSubtitle').textContent=`已保存 ${state.resultRows.length} 张图片结果，找到 ${totalProducts} 个商品`;$('#statsRow').innerHTML='';$('#statsRow').appendChild(makeStatsCard('搜索图片数',state.resultRows.length,false));$('#statsRow').appendChild(makeStatsCard('找到商品数',totalProducts,true));$('#statsRow').appendChild(makeStatsCard('平均结果/图',state.resultRows.length?(totalProducts/state.resultRows.length).toFixed(1):'0',false));$('#statsRow').appendChild(makeStatsCard('接口总耗时',fmtClock((Date.now()-state.pollStartedAt)/1000),false));renderPage()}
function makeStatsCard(label,val,primary){return h('div',{class:'stats-card'+(primary?' primary':'')},h('div',{class:'stat-label'},label),h('div',{class:'stat-value'},String(val)))}
function renderPage(){const list=$('#resultList');list.innerHTML='';const page=state.pagination.currentPage,size=state.pagination.pageSize,total=state.resultRows.length,start=(page-1)*size,end=Math.min(start+size,total),rows=state.resultRows.slice(start,end);if(!rows.length){list.appendChild(h('div',{class:'empty-state'},h('div',{class:'empty-state-icon'},'🔍'),h('p',{},'未找到匹配的商品')));$('#paginationWrap').hidden=true;return}rows.forEach(row=>{const wrap=h('div',{class:'result-row'});wrap.appendChild(h('div',{class:'result-source'},h('img',{src:sourceImage(row.item),alt:row.item.name,loading:'lazy'})));const mini=h('div',{class:'result-mini-cards'});row.products.slice(0,5).forEach((p,i)=>mini.appendChild(buildMiniCard(p,i+1)));wrap.appendChild(mini);if(row.products.length>5){const more=h('div',{class:'result-more'});const btn=h('button',{class:'btn-view-more',type:'button'},`查看更多 +${row.products.length-5}`);on(btn,'click',()=>openResultModal(row));more.appendChild(btn);wrap.appendChild(more)}list.appendChild(wrap)});const pages=Math.max(1,Math.ceil(total/size));$('#paginationWrap').hidden=total<=size;$('#paginationInfo').textContent=`第 ${start+1}-${end} 条，共 ${total} 条`;$('#pageCurrentNum').textContent=page;$('#pageTotalNum').textContent=pages;$('#pagePrev').disabled=page<=1;$('#pageFirst').disabled=page<=1;$('#pageNext').disabled=page>=pages;$('#pageLast').disabled=page>=pages}
function buildMiniCard(item,rank){const node=$('#miniCardTemplate').content.firstElementChild.cloneNode(true);node.href=item.url||'#';node.querySelector('img').src=item.image||emptySvg;node.querySelector('.mini-title').textContent=item.title;node.querySelector('.mini-rank').textContent='#'+rank;node.querySelector('.mini-price').textContent=item.price||'-';node.querySelector('.mini-moq').textContent=item.discount||'';const sales=node.querySelector('.mini-sales-row');sales.innerHTML=item.sales?`<span class="mini-sales-item">${escapeHtml(item.sales)}</span>`:'';sales.style.display=item.sales?'':'none';const meta=node.querySelector('.mini-meta');meta.innerHTML=item.goodsId?`<span class="mini-meta-item">ID ${escapeHtml(item.goodsId)}</span>`:'';node.querySelector('.mini-ad-badge').style.display=item.is_ad?'':'none';return node}
function buildFullCard(item,rank){const node=$('#productCardTemplate').content.firstElementChild.cloneNode(true);node.href=item.url||'#';node.querySelector('img').src=item.image||emptySvg;node.querySelector('.product-title').textContent=item.title;node.querySelector('.product-price').textContent=item.price||'-';node.querySelector('.product-meta').innerHTML=[item.goodsId?`<span class="meta-item">ID ${escapeHtml(item.goodsId)}</span>`:'',item.discount?`<span class="meta-item">${escapeHtml(item.discount)}</span>`:''].join('');const sales=node.querySelector('.product-sales-row');sales.innerHTML=item.sales?`<span class="product-sales-item">${escapeHtml(item.sales)}</span>`:'';sales.style.display=item.sales?'':'none';node.querySelector('.product-ad-badge').style.display=item.is_ad?'':'none';node.querySelector('.similarity-fill').style.width=Math.max(10,Math.min(100,(item.similarity||Math.max(.1,1-rank/50))*100))+'%';return node}
function openResultModal(row){$('#resultModalThumb').src=sourceImage(row.item);$('#resultModalTitle').textContent=row.item.name;$('#resultModalSub').textContent=`共 ${row.products.length} 个结果 · ${label(row.item.status)}`;const grid=$('#resultModalGrid');grid.innerHTML='';row.products.forEach((p,i)=>grid.appendChild(buildFullCard(p,i+1)));$('#resultModal').hidden=false}
function closeResultModal(){$('#resultModal').hidden=true}
function setupPagination(){on($('#pageFirst'),'click',()=>{state.pagination.currentPage=1;renderPage()});on($('#pagePrev'),'click',()=>{state.pagination.currentPage=Math.max(1,state.pagination.currentPage-1);renderPage()});on($('#pageNext'),'click',()=>{state.pagination.currentPage=Math.min(Math.ceil(state.resultRows.length/state.pagination.pageSize),state.pagination.currentPage+1);renderPage()});on($('#pageLast'),'click',()=>{state.pagination.currentPage=Math.max(1,Math.ceil(state.resultRows.length/state.pagination.pageSize));renderPage()});on($('#pageJumpBtn'),'click',()=>{const max=Math.max(1,Math.ceil(state.resultRows.length/state.pagination.pageSize));const v=Number($('#pageJumpInput').value);if(v>=1&&v<=max){state.pagination.currentPage=v;renderPage()}});on($('#pageSizeSelect'),'change',e=>{state.pagination.pageSize=Number(e.target.value)||20;state.pagination.currentPage=1;renderPage()})}
function renderHistory(){const list=$('#historyList');const batches=state.batch?[state.batch]:[];if(!batches.length){list.innerHTML='<span class="muted">暂无任务记录</span>';return}list.innerHTML='';batches.forEach(b=>{const s=b.summary||{};const item=h('div',{class:'history-item'},h('div',{class:'history-info'},h('span',{class:`status-badge status-${b.status}`},label(b.status)),h('strong',{},`批次 ${b.id.slice(0,8)}`),h('span',{class:'muted'},`${(s.succeeded||0)+(s.failed||0)}/${s.total||0} · ${b.items.reduce((sum,x)=>sum+(x.productCount||x.products?.length||0),0)} 个商品`)),h('div',{class:'history-actions'}));const stop=h('button',{class:'btn btn-danger btn-sm'},'停止并清理');on(stop,'click',()=>stopAndCleanup());item.querySelector('.history-actions').appendChild(stop);list.appendChild(item)})}
async function stopAndCleanup(){if(!state.batch?.id)return;state.cancelRequested=true;$('#cancelBtn').disabled=true;$('#cancelBtn').textContent='正在清理...';try{await fetchJson(`/api/temu/tasks/${state.batch.id}/cancel`,{method:'POST'});unregisterOwnedBatch(state.batch.id);state.batch=null;state.resultRows=[];stopPolling();state.isSearching=false;$('#progressStatus').textContent='⏹ 已停止任务，结果已清理';$('#cancelBtn').hidden=true;$('#result-section').hidden=true;renderHistory();updateSearchBtn()}catch(e){alert('停止任务失败：'+e.message);$('#cancelBtn').disabled=false;$('#cancelBtn').textContent='⏹ 停止任务'}}
function cleanupBatch(id,useBeacon=false){if(!id||state.cleanupSent.has(id))return;state.cleanupSent.add(id);const encoded=encodeURIComponent(id);const cleanupUrl=`${state.apiBase}/api/temu/tasks/${encoded}/cleanup`;if(useBeacon&&navigator.sendBeacon){try{const ok=navigator.sendBeacon(cleanupUrl,new Blob([], {type:'text/plain'}));if(ok){unregisterOwnedBatch(id);return}}catch{}}const url=useBeacon?cleanupUrl:`${state.apiBase}/api/temu/tasks/${encoded}`;fetch(url,{method:useBeacon?'POST':'DELETE',keepalive:true}).then(()=>unregisterOwnedBatch(id)).catch(()=>{state.cleanupSent.delete(id);registerOwnedBatch(id)})}
function cleanupOwned(useBeacon=false){[...state.ownedBatchIds].forEach(id=>cleanupBatch(id,useBeacon))}
function setupSettings(){on($('#settingsBtn'),'click',openSettings);on($('#settingsClose'),'click',closeSettings);on($('#settingsCancel'),'click',closeSettings);on($('#settingsOverlay'),'click',closeSettings);on($('#settingsSave'),'click',()=>{setApiBase($('#apiBaseInput').value);closeSettings();testConnection()})}
function openSettings(){$('#apiBaseInput').value=state.apiBase;$('#settingsModal').hidden=false;testConnection()}
function closeSettings(){$('#settingsModal').hidden=true}
async function testConnection(){const dot=$('#connectionStatus .status-dot'),text=$('#connectionStatus .status-text');dot.className='status-dot checking';text.textContent='检测中...';try{const data=await fetchJson('/api/health');dot.className='status-dot success';text.textContent=`连接成功 · ${data.mode==='mock'?'演示模式':'真实设备'}`}catch(e){dot.className='status-dot error';text.textContent='连接失败：'+e.message}}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove()}
function init(){setupTabs();setupBatchUpload();setupUrlPanel();setupTablePanel();setupPagination();setupSettings();on($('#noticeClose'),'click',()=>$('#apiNotice').hidden=true);on($('#clearBtn'),'click',clearCurrent);on($('#searchBtn'),'click',startSearch);on($('#cancelBtn'),'click',stopAndCleanup);on($('#refreshHistoryBtn'),'click',renderHistory);on($('#newSearchBtn'),'click',()=>{cleanupOwned(false);state.batch=null;state.resultRows=[];$('#result-section').hidden=true;$('#progress-section').hidden=true;renderHistory();window.scrollTo({top:0,behavior:'smooth'})});on($('#exportJsonBtn'),'click',()=>state.batch&&download(`${state.apiBase}/api/temu/tasks/${state.batch.id}/export?format=json`,'temu-results.json'));on($('#exportCsvBtn'),'click',()=>state.batch&&download(`${state.apiBase}/api/temu/tasks/${state.batch.id}/export?format=csv`,'temu-results.csv'));on($('#resultModalClose'),'click',closeResultModal);on($('#resultModalOverlay'),'click',closeResultModal);window.addEventListener('pagehide',()=>cleanupOwned(true));window.addEventListener('beforeunload',()=>cleanupOwned(true));cleanupOwned(false);testConnection();updateSearchBtn();renderHistory()}
init();
})();
